name: 'Add Remove Label'
description: 'add or remove pull requests label'
branding:
  icon: 'edit'  
  color: 'yellow'
inputs:
  token:
    description: 'github token'
    required: true
    default: ''
  labels:
    description: 'labels to edit'
    required: false
    default: ''
  label:
    description: 'label to edit'
    required: false
    default: ''
  type:
    description: 'add or remove'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
